import assert from 'node:assert/strict';
import { estadoCamara, observarRecuperacion } from '../web/js/salud_camaras.js';
const saludable = { online: true, connected: true, segundos_sin_senal: 2, enabled: true };
assert.equal(estadoCamara(saludable, {}).clave, 'en-linea');
assert.equal(estadoCamara({...saludable, connected: false}, {}).clave, 'reconectando');
assert.equal(estadoCamara({...saludable, segundos_sin_senal: 60}, {}).clave, 'sin-senal');
assert.equal(estadoCamara({...saludable, segundos_sin_senal: null}, {}).clave, 'sin-senal');
assert.equal(estadoCamara({...saludable, enabled: false}, {}).clave, 'deshabilitada');
assert.equal(estadoCamara(saludable, null).clave, 'procesando');
assert.equal(estadoCamara(saludable, {}, true).clave, 'error-video');
let observacion = observarRecuperacion(null, 'en-linea', 0);
observacion = observarRecuperacion(observacion, 'reconectando', 1000);
observacion = observarRecuperacion(observacion, 'sin-senal', 4000);
observacion = observarRecuperacion(observacion, 'en-linea', 9000);
assert.equal(observacion.recuperacion, 8);
assert.equal(observacion.caida, null);
observacion = observarRecuperacion(observacion, 'en-linea', 11000);
assert.equal(observacion.recuperacion, 8);
let apagada = observarRecuperacion(null, 'sin-senal', 1000);
apagada = observarRecuperacion(apagada, 'en-linea', 6000);
assert.equal(apagada.recuperacion, null, 'No inventar una recuperación de una cámara nunca vista en línea');
console.log('Estado, cuadros antiguos, recuperación y arranque sin señal: OK');
